### ISSUE TITLE
timeout设置为-1永不过期的一个bug

### ISSUE THREAD

**Issue by zjh599245299** [click33/sa-token#5]
当设置为永不过期的时候,同一个用户在A浏览器登录成功, B再在另一个浏览器登录成功, 此时刷新A会提示被踢下线, 但是如果此时A再登录一次, B那边不提示被踢下线, 会有两个token同时可以使用.
当设置过期时间的时候 两个用户不能同时在线就正常

**Comment by click33** [comment]
用的哪个版本

**Comment by zjh599245299** [comment]
> 用的哪个版本

1.9.0

**Comment by click33** [comment]
v1.10.0已修复此问题，请更新
